### PR TITLE
Example for using DocFormer

### PR DESCRIPTION
**Pull request by uakarsh**
Contains a sample code for training docformer

### CODE REVIEW

**Comment by gloitongbam** [comment]
Hi @uakarsh and @shabie, thank you for providing the implementation of Docforme and examples to understand the methods. 

In this post, I would like to understand the file named 'rvl_cdip_dataset.csv' you have used in the [docformer](https://github.com/shabie/docformer)/[examples](https://github.com/shabie/docformer/tree/master/examples)/dataset_creation_for_docformer.py file. I could not figure out what is the structure of this file. Please provide the file structure of this mentioned CSV file to know better. 

Thanks,
Gyanendro

**Comment by uakarsh** [comment]
> Hi @uakarsh and @shabie, thank you for providing the implementation of Docformer and examples to understand the methods.
> 
> In this post, I would like to understand the file named 'rvl_cdip_dataset.csv' you have used in the [docformer](https://github.com/shabie/docformer)/[examples](https://github.com/shabie/docformer/tree/master/examples)/dataset_creation_for_docformer.py file. I could not figure out what is the structure of this file. Please provide the file structure of this mentioned CSV file to know better.
> 
> Thanks, Gyanendro

Hi there, 

Actually, this part was quite initial, and it was just a rough work kind of thing (this CSV has not been used anywhere, and we would remove it).

Meanwhile, I would suggest that, if you want to use DocFormer, you can open the colab notebook, which I have shared for the purpose of MLM, and extend it further for your usecase.

And, feel free to ping, if you have more questions on the same. Happy to help.

Akarsh

**Comment by uakarsh** [comment]
This code would help for using DocFormer for the task of MLM

**Comment by gloitongbam** [comment]
Thank you so much Akarsh... I will go through the colab notebook... Thanks a lot...

**Pull request merged**
